services:
  db:
    image: postgres:16
    container_name: db-health
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    networks:
      - micro_net

  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: health_backend
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Database=postgres;Username=postgres;Password=root;"
    ports:
      - "5102:8080"
    restart: always
    networks:
      - micro_net

volumes:
  postgres_data:

networks:
  micro_net:
    external: true
